# Generated by Django 6.0.4 on 2026-04-24 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0004_attendancesummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluator_type', models.CharField(choices=[('student', 'Student'), ('peer', 'Peer'), ('admin', 'Admin')], default='student', max_length=20)),
                ('evaluation_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('remarks', models.TextField(blank=True)),
                ('term', models.CharField(max_length=30)),
                ('school_year', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='academics.facultyprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
