# Generated by Django 6.0.4 on 2026-04-28 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyevaluation',
            name='evaluator_type',
            field=models.CharField(choices=[('student', 'Student'), ('peer', 'Peer'), ('admin', 'Admin'), ('self', 'Self-Evaluation')], default='student', max_length=20),
        ),
    ]
