# Generated by Django 6.0.4 on 2026-04-28 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0005_advisorysection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('material_type', models.CharField(choices=[('lesson', 'Lesson'), ('module', 'Module'), ('presentation', 'Presentation'), ('handout', 'Handout'), ('activity', 'Activity'), ('reference', 'Reference'), ('link', 'External Link')], default='lesson', max_length=30)),
                ('file', models.FileField(blank=True, null=True, upload_to='lesson_materials/')),
                ('external_link', models.URLField(blank=True)),
                ('visibility', models.CharField(choices=[('all', 'All Users'), ('students', 'Students Only'), ('faculty', 'Faculty Only')], default='all', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('class_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_materials', to='academics.classsection')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_materials', to='academics.subject')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_lesson_materials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
