# Generated by Django 6.0.4 on 2026-04-22 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_total', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('activity_total', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('exam_total', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('lab_total', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('attendance_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('final_grade', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('remarks', models.CharField(blank=True, max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='academics.enrollment')),
            ],
            options={
                'ordering': ['enrollment__class_section', 'enrollment__student__student_number'],
            },
        ),
    ]
