# Generated by Django 6.0.4 on 2026-04-27 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_attendancesummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisorySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=50)),
                ('year_level', models.CharField(max_length=10)),
                ('term', models.CharField(max_length=30)),
                ('school_year', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adviser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advisory_sections', to='academics.facultyprofile')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisory_sections', to='academics.department')),
            ],
            options={
                'ordering': ['department__code', 'year_level', 'section_name'],
                'unique_together': {('section_name', 'term', 'school_year')},
            },
        ),
    ]
